### ISSUE TITLE
errors about video transmission on raspberrypi 

### ISSUE THREAD

**Issue by Githubwujinming** [dji-sdk/Tello-Python#50]
runned in raspberrypi , python2.7 , environments descriped in ./linux_install.sh were installed.
Getting the following error. 
![error image](https://user-images.githubusercontent.com/28724132/70032687-ed890f80-15e8-11ea-8e8a-ae23e458684f.jpg)

1.error while decoding MB 22 11, bytestream -12
2.non-existing pps 0 referenced
i think there something wrong with ffmpeg and libh264decoder. so how to fix it ?
appreciate for your help

**Comment by dji-dev** [comment]
Public comment from Ho.Yan in <a href='https://djisdksupport.zendesk.com/agent/tickets/30418'>Zendesk ticket #30418</a>:<br><br>Dear Developer,

Thanks for reaching Ryze!

Have you modified the original code?

Thanks and have a nice day!

Regards,
RYZE TECHNICAL SUPPORT

**Comment by Githubwujinming** [comment]
Thank you for your response, it works on PC without error,  raspberrypi may not power enough to real-time decode h264 package , so that only  part of the image was decoded.  is there any possibility to make it work on raspberrypi ? any suggestions are welcome.

**Comment by dji-dev** [comment]
Public comment from Ho.Yan in <a href='https://djisdksupport.zendesk.com/agent/tickets/30418'>Zendesk ticket #30418</a>:<br><br>Dear Developer,

Thanks for reaching Ryze!

Raspberrypi is not our official recommendation and may require you to test it yourself.

Thanks and have a nice day!

Regards,
RYZE TECHNICAL SUPPORT
