### ISSUE TITLE
how to reduce the delay of video stream

### ISSUE THREAD

**Issue by alexmihalyk23** [dji-sdk/Tello-Python#60]
I'am use opencv and imutils library's for capture video(imutils - filevideostream), but get delay on stream. How to fix this?

**Comment by dji-dev** [comment]
Public comment from Ho.Yan in <a href='https://djisdksupport.zendesk.com/agent/tickets/31542'>Zendesk ticket #31542</a>:<br><br>Dear Developer,
Thank you for contacting DJI.

This question you can contact RYZE Tello's technical support：
support.cn@ryzerobotics.com

Warm Regards,
DJI Developer Support

**Comment by alexmihalyk23** [comment]
I'am fixed it using WebcamVideostream

**Comment by manujimele** [comment]
> I'am fixed it using WebcamVideostream

How have you done that @alexmihalyk23?

I have issues trying to get frames from the camera.
Any info? any help?

**Comment by luohc2004** [comment]
Can I obtain the picture taken from the down side bottom view camera?

**Comment by alexmihalyk23** [comment]
@Manujimele https://github.com/jrosebr1/imutils/blob/master/imutils/video/webcamvideostream.py

**Comment by Marselias** [comment]
Does anyone have a better solution? WebcamVideostream only provides threading, which wasn't helpful for me.
