### ISSUE TITLE
How can I get frame for YOLOv2

### ISSUE THREAD

**Issue by ozanpkr** [dji-sdk/Tello-Python#63]
How can I read frame from tello udp.When I used djıtellopy 1.5 ı get very low fps.Please help me.And ı get this error;
                    [h264 @ 0000025498d6df80] error while decoding MB 17 34, bytestream -12
                    [h264 @ 0000025498dbbc40] error while decoding MB 42 8, bytestream -9
                    [h264 @ 00000254992168c0] error while decoding MB 3 25, bytestream -8
                    [h264 @ 0000025498d6d840] error while decoding MB 47 43, bytestream -8

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/31838'>Zendesk ticket #31838</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, that the TelloSDK only provides the standard H264 data but not the YOLO.
You can refer to the following files:
https://github.com/dji-sdk/Tello-Python/tree/master/Tello_Video/h264decoder

Thanks,

Luce Luo
DJI Dev Team
