### ISSUE TITLE
Tello_state

### ISSUE THREAD

**Issue by PaulHermens** [dji-sdk/Tello-Python#7]
I don't know why with me it did but, my tello just broke because of your script. tello_state.py has ripped it. If I start my tello now it immediately turns off again. Help would be nice.

**Comment by hanker-lu** [comment]
I am sorry that I did not respond to you in time. Has your problem been resolved?

**Comment by hknakata** [comment]
> I am sorry that I did not respond to you in time. Has your problem been resolved?

I fixed it by using python 2.7

**Comment by PaulHermens** [comment]
Well done. It has been fixed
