### ISSUE TITLE
Can I obtain the picture taken from the down side bottom view camera via SDK?

### ISSUE THREAD

**Issue by luohc2004** [dji-sdk/Tello-Python#72]
Can I obtain the picture taken from the down side bottom view camera via SDK?

**Comment by dji-dev** [comment]
Agent comment from Ho.Yan in <a href='https://djisdksupport.zendesk.com/agent/tickets/39383'>Zendesk ticket #39383</a>:<br><br>Dear Developer,
Thank you for contacting DJI.

This question you can contact RYZE Tello's technical support：
support.cn@ryzerobotics.com

Thanks for your understanding and patience.
Warm Regards,
DJI Developer Support

**Comment by luohc2004** [comment]
I contact RYZE, and the answer is " Sorry that the TelloSDK doesn't support to access the downward camera."

**Comment by luohc2004** [comment]
I contact RYZE, and the answer is " Sorry that the TelloSDK doesn't support to access the downward camera."
