### ISSUE TITLE
get frame from Bottom camera

### ISSUE THREAD

**Issue by NowLoadY** [dji-sdk/Tello-Python#90]
is it possible to get images from bottom camera？

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/73371'>Zendesk ticket #73371</a>:<br><br>Tello edu and robomaster tello talent support get images from bottom camera.
However, white tello does not support this function
<br><p><em><small>°°°</small></em></p>

**Comment by NowLoadY** [comment]
OK，...Thanks for your reply！
